/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostsImport } from './routes/posts'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedLayoutBImport } from './routes/_protected/layout-b'
import { Route as ProtectedHomeImport } from './routes/_protected/home'

// Create/Update Routes

const PostsRoute = PostsImport.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
})

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
})

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const ProtectedLayoutBRoute = ProtectedLayoutBImport.update({
  path: '/layout-b',
  getParentRoute: () => ProtectedRoute,
})

const ProtectedHomeRoute = ProtectedHomeImport.update({
  path: '/home',
  getParentRoute: () => ProtectedRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProtectedRoute: ProtectedRoute.addChildren({
    ProtectedHomeRoute,
    ProtectedLayoutBRoute,
  }),
  PostsRoute,
})

/* prettier-ignore-end */
